<a href="https://colab.research.google.com/github/Majsh29/Dummy-Repo-Colab/blob/main/ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nueva sección

In [ ]:
a=int(input("ingresa Tu Numero: "))
b=int(input("ingresa Tu Numero: "))
print("La Suma es: ",a+b)
print("La Resta es: ",a-b)
print("La Multiplicacion es: ",a*b)
print("La Division es: ",a/b)

KeyboardInterrupt: Interrupted by user

# Sección nueva

In [ ]:
tu_nombre = "jian"
tu_apellido = "sanchez"

In [ ]:
# 2. El Registro Sucio
registro_sucio = " ##[ID-9875]__Monto:S/.4500__Estado:PENDIENTE## "

In [ ]:
Texto_limpio = registro_sucio.strip(" #")
texto_limpio

In [ ]:
texto_minuscula = texto_limpio.lower()
texto_minuscula

In [ ]:
texto_reemplazado = texto_minuscula.replace("pendiente","procesado")
texto_reemplazado

In [ ]:
Lista = texto_reemplazado.split("__")
Lista

In [ ]:
parte_monto = Lista[1]
print(parte_monto)

In [ ]:
indice_m = parte_monto.index("m")
indice_m

In [ ]:
print(f"Reporte generado por {tu_nombre} {tu_apellido}. El texto final limpio y dividido es: {Lista}. La 'm' de monto se encontró en la posición: {indice_m}")

while# Sección nueva

In [ ]:
condTrue = True
while condTrue:
   print("Mientras la condicion sea Verdadera")

In [ ]:
condTrue = True
contador = 0
limite = 5 # Set a limit for the loop

while condTrue:
   print("Mientras la condicion sea Verdadera")
   contador = contador + 1
   if contador >= limite:
        condTrue = False # Set condTrue to False to exit the loop

In [ ]:
tope = 5
numero = 1
while numero <= tope:
    print(f'Este es el intento numero {numero}')
    numero = numero + 1

        # Es vital sumar 1 al contador, de lo contrario será 1 por siempre.

In [ ]:
dni = ''

while not(len(dni) == 8):
  dni = str(input("Ingrese un dni con 8 digitos: "))

In [ ]:
venta_bruta = 450.50
impuesto = venta_bruta * 0.18

total_facturado = round(venta_bruta + impuesto, 2)

print(f"Reporte: La venta bruta fue ${venta_bruta}, total con impuestos: ${total_facturado}")

# PROYECTO 2

In [ ]:
log_crudo = "$$[ESTADO:ok]||trx_id:9934||monto:S/.1250.50||alerta:falso$$ "

In [ ]:
Limpio = log_crudo.strip(" $")
Limpio

In [ ]:
Mayuscula = Limpio.upper()
Mayuscula

In [ ]:
Lista_Campos = Mayuscula.split("||")
print(Lista_Campos)

In [ ]:
Parte_Monto_Completa = Lista_Campos[-2]
print(Parte_Monto_Completa)

In [ ]:
Monto_str = Parte_Monto_Completa[len("MONTO:S/."):]
print(Monto_str)

In [ ]:
Monto_Transaccion = float(Monto_str)
print(Monto_Transaccion)

In [ ]:
umbrales_auditoria = (500.0, 2000.0)

In [ ]:
if umbrales_auditoria[1] < Monto_Transaccion:
 print("ALERTA ROJA: Transacción bloqueada. Supera los $2000." )
elif umbrales_auditoria[1] >= Monto_Transaccion > umbrales_auditoria[0]:
 print("ALERTA AMARILLA: Transacción enviada a revisión manual." )
else:
 print("VERDE: Transacción procesada automáticamente." )

In [ ]:
reporte_diario = {"fecha": "2026-06-07",
                  "lotes_procesados": [350.0, 1250.50, 90.0, 2100.0],
                  "operador": "Jian Franco Sanchez Ramirez"}

In [ ]:
# enumarate ( lista ,(sin nada = 0) donde inicia )
for indice, monto in enumerate(reporte_diario["lotes_procesados"] , start=1):
 print(f"Lote N° {indice} procesado por un valor de ${monto}")

intentos = 1
while intentos <= 3:
    print(f"Intentando conectar al servidor de destino... Intento {intentos}")
    intentos += 1

# TEORIA TERCERA CLASE

In [ ]:
base_clientes = [
    {"id": 101,
     "nombre": "Ana",
     "coordenadas": (-12.04, -77.02),
     "activo": True},
    {"id": 102,
     "nombre": "Luis",
     "coordenadas": (-12.08, -77.05),
     "activo": False},
    {"id": 103,
     "nombre": "Carmen",
     "coordenadas": (-12.10, -77.01),
     "activo": True}
]

# 1. ¿Cómo extraigo el nombre del segundo cliente?
nombre_segundo = base_clientes[1]["nombre"]

#2. Latitud del tercer cliente
latitud_tercer = base_clientes[2]["coordenadas"][0]
longitud_tercer = base_clientes[2]["coordenadas"][1]


print(f"El nombre del segundo cliente es {nombre_segundo}")
print(f"La latitud del tercer cliente es {latitud_tercer}")
print(f"La longitud del tercer cliente es {longitud_tercer}")

In [ ]:
tabla_ventas = {
    "ticket_id": (1, 2, 3), # Tupla (No queremos que los IDs cambien)
    "monto": [150.5, 200.0, 99.9], # Lista (Podemos sumar montos)
    "estado": ["Pagado", "Pagado", "Pendiente"] # Lista
}

tabla_ventas["monto"].append(350.0)
tabla_ventas["estado"].append("Pendiente")

print(f"La tabla actualizada de montos seria: {tabla_ventas["monto"]}")
print(f"La tabla actualizada de estado seria: {tabla_ventas["estado"]}")

In [ ]:
respuesta_servidor = {
    "tienda": "TechStore",
    "productos": [
        {"nombre": "Mouse", "precio": 50, "descuento": 5},
        {"nombre": "Laptop Gamer", "precio": 1500, "descuento": 200}
    ]
}

Precio = respuesta_servidor["productos"][1]["precio"]
Descuento = respuesta_servidor["productos"][1]["descuento"]
Total = Precio - Descuento
print(f" La Laptop Gamer cuesta finalmente {Total}")

In [ ]:
# Ingresa a precio de laptop y restar 200 al precio original
precio_laptop = respuesta_servidor["productos"][1]["precio"]
descuento_laptop = respuesta_servidor["productos"][1]["descuento"]

precio_final = precio_laptop - descuento_laptop

print(f'El precio original de la laptop es: {precio_laptop}')
print(f'El precio actualizado de la laptop es: {precio_final}')

#FUNCIONES

In [ ]:
precio_cartera = 100

impuesto = precio_cartera*0.18
precio_final_cartera = precio_cartera + impuesto

print(f'El precio final de la cartera es: {precio_final_cartera}')

In [ ]:
precio_pelota = 70

impuesto = precio_pelota*0.18
precio_final_pelota = precio_pelota + impuesto

print(f'El precio final de la cartera es: {precio_final_pelota}')

In [ ]:
def calcular_precio_final(precio_producto):
    impuesto = precio_producto*0.18
    precio_final = precio_producto + impuesto
    return precio_final

In [ ]:
calcular_precio_final(200)

In [ ]:
def aplicar_descuento(precio, descuento):
    precio_final = precio - descuento
    return precio_final

In [ ]:
aplicar_descuento(1500,200)

El equipo de Marketing extrajo una lista de teléfonos de clientes desde una página web, pero los usuarios escriben de formas muy raras (con guiones, espacios extra, etc.). Necesitamos una función que reciba esa lista sucia y devuelva una lista perfectamente limpia para subirla al sistema de mensajería (SMS).

In [ ]:
def limpiar_telefono(lista_telefonos):
  lista_numeros_limpios = []

  for numero in lista_telefonos:
    numero_limpio = numero.replace("-","").replace(" ","").strip()
    lista_numeros_limpios.append(numero_limpio)

  #lista_numeros_limpios = ["987654321","999888777","987987987"]
  return lista_numeros_limpios

In [ ]:
telefonos = ["  987-654-321","999 888 777","987-987-987  ","  987-654----321","999 888 777","987-987-987  "]

lista_numeros_limpios = limpiar_telefono(telefonos)
print(lista_numeros_limpios)

Recibimos la lista de ventas del día de un asesor comercial. La regla de la empresa es:

Si la venta es mayor a $1000, gana el 10% de comisión.

Si la venta está entre  500y 1000, gana el 5%.

Si la venta es menor a $500, no gana comisión (0%).

Queremos una función que calcule cuánto dinero extra se llevará el asesor hoy.


[ ]

In [ ]:
ventas_asesor_A = [1200, 300]

In [ ]:
def calcule_pago_comisiones(lista_ventas):
  total_comision = 0 #Inicializar el acumulador de comisiones

  for venta in lista_ventas:
    if venta > 1000:
      total_comision = total_comision + venta*0.1
    elif venta >= 500:
      total_comision = total_comision + venta*0.05

  return total_comision

In [ ]:
comision_asesor_A = calcule_pago_comisiones(ventas_asesor_A)
print(comision_asesor_A)

In [ ]:
def comision_venta(lista_venta):
  total_comision = 0
  for venta in lista_venta:
    if venta > 1000:
        total_comision = total_comision + venta * 0.1
    elif venta > 500 and venta < 1000:
        total_comision = total_comision + venta * 0.05

  return total_comision

lista_venta = [600, 1500.5, 501, 360]
comision = comision_venta(lista_venta)
print(f"El asesor ganará ${round(comision,2)} de comisión.")

# Manejo de Errores (try y except)

In [ ]:
numeros_denominador = [2,5,0,10]
numerador = 10
# fraccion--> numerador / denominador

for num in numeros_denominador:
  # Intentes hacer esto...
  try:
    resultado = numerador / num
    print(f'{numerador} / {num} = {resultado}')
  except:
    print(f'No se puede dividir {numerador} entre {num}')

In [ ]:
numeros = [2,5,"Gratis",10]
numerador = 10
# fraccion--> numerador / denominador

for num in numeros:
  # Intentes hacer esto...
  try:
    resultado = numerador / num
    print(f'{numerador} / {num} = {resultado}')
  except Exception as e:
    print(f'Hubo un error al procesar {num}. El sistema dice que el error fue: {e}')

In [ ]:
cliente = {
    "nombre": "Angel",
    "edad": 28
}
try:
  print(cliente["apellido"])
except KeyError as e:
  print(f'Hubo un error al procesar el cliente. El sistema dice que el error fue: {e}')

List Comprehension (Listas en una sola linea) -- FOR
[QUE_QUIERO_HACER for VARIABLE in LISTA_ORIGINAL]

In [ ]:
# El for clasico
numeros_viejos = [10,20,30]
numeros_nuevos = []  # Voy a sumarle +2 a cada elemento de lista vieja

for numero in numeros_viejos:
  numeros_nuevos.append(numero + 2)

print(numeros_nuevos)

In [ ]:
# El for en una linea
numeros_nuevos = [numero + 2 for numero in numeros_viejos]
print(numeros_nuevos)

In [ ]:
## Volver mayusculas los nombres de la lista

nombres_list = ["Ana","Erika","Yami"]
nombres_list_mayus = [ nombre.upper()  for nombre in nombres_list]
print(nombres_list_mayus)

List Comprehension (Listas en una sola linea) -- IF
[QUE_QUIERO_HACER for VARIABLE in LISTA_ORIGINAL if CONDICION]

In [ ]:
edades_list = [15,22,30,12]

mayor_edad = [ edad for edad in edades_list if edad >= 18]
print(mayor_edad)

menor_edad = [ edad for edad in edades_list if edad < 18]
print(menor_edad)

# LABORATORIO 3

In [ ]:
respuesta_api = [
    {"trx_id": "T001", "monto_usd": 150.00, "estado": "Completado"},
    {"trx_id": "T002", "monto_usd": "Error_Red", "estado": "Fallido"},
    {"trx_id": "T003", "monto_usd": 320.50, "estado": "Completado"},
    {"trx_id": "T004", "monto_usd": 45.00, "estado": "Completado"}
]

In [ ]:
def extraer_montos(lista_datos):
    """
    Recorre una lista de diccionarios y extrae únicamente los valores de 'monto_usd'.
    """
    lista_montos = []
    for registro in lista_datos:
        # Extraemos el valor asociado a la llave "monto_usd" en cada ciclo
        monto = registro["monto_usd"]
        lista_montos.append(monto)
    return lista_montos

In [ ]:
# Prueba de la Parte 1
montos_extraidos = extraer_montos(respuesta_api)
print("1. Montos extraídos de la API:", montos_extraidos)

In [ ]:
def convertir_a_soles(monto):
    """
    Convierte un monto en dólares a soles (tipo de cambio 3.8).
    Incluye un mecanismo de seguridad para evitar colapsos por datos corruptos.
    """
    # IMPLEMENTACIÓN DEL TRY/EXCEPT:
    # Se utiliza este bloque porque sabemos que la API envía ocasionalmente texto
    # en lugar de números (ej. "Error_Red"). Si intentamos multiplicar un texto,
    # Python lanzará un TypeError y detendrá todo el sistema. El try/except
    # 'atrapa' ese error, reporta el problema y permite que el código siga fluyendo.
    try:
        conversion = monto * 3.8
        return round(conversion, 2)
    except Exception as e:
        print(f"\n⚠️ Alerta: Dato corrupto detectado. Detalle: [{e}]")
        return 0

In [ ]:
convertir_a_soles(montos_extraidos)

In [ ]:
# Lista proporcionada por el área de Finanzas
montos_limpios = [570.0, 0, 1217.9, 171.0, 850.0, 90.0]

# List Comprehension: [resultado FOR elemento IN lista IF condición]
# Multiplicamos por 0.18 para sacar el impuesto, redondeamos a 2 decimales,
# y aplicamos el filtro estricto de > 500.0
impuestos_grandes = [round(monto * 0.18, 2) for monto in montos_limpios if monto > 500.0]

print("\n3. Impuestos de transacciones grandes:", impuestos_grandes)

In [ ]:
# Calculamos la suma total de la lista filtrada
suma_total_impuestos = sum(impuestos_grandes)

# Reporte final utilizando f-string y caracteres de escape (\n) para saltos de línea
reporte_final = f"""
======================================
         REPORTE DE AUDITORÍA
======================================
Total de impuestos extraídos: {len(impuestos_grandes)} registros.
Suma total de impuestos a retener: S/ {suma_total_impuestos}
======================================\nOperación finalizada sin interrupciones del sistema.
"""

In [ ]:
print(reporte_final)

In [ ]:
marcas = ["apple","samsung", "lenovo"]
for i , v in enumerate(marcas,1):
 if i == 2:
  print(v)

In [ ]:
valores = [10,20]
valores.append([30,40])
print(len(valores))

# CLASE 4

In [ ]:
diccionario_ventas = {
    "id_venta": [101,102,103],
    "cliente": ["Ana","Luis","Carlos"],
    "monto": [150.50,300.00,85.00]
}

In [ ]:
import pandas as pd

In [ ]:
#Convertir el diccionario en un Dataframe (Tabla de Excel)
df_ventas = pd.DataFrame(diccionario_ventas)

In [ ]:
display(df_ventas)

In [ ]:
#en colab sale la tabla en python tienes que poner display
pd.DataFrame({
    "id_venta": [101,102,103],
    "cliente": ["Ana","Luis","Carlos"],
    "monto": [150.50,300.00,85.00]
})

In [ ]:
url_archivo = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"

In [ ]:
df_archivo = pd.read_csv(url_archivo)

In [ ]:
print("informacion del archivo")
display(df_archivo)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#En el colab
url_archivo_colab_rrhh = "/content/rrhh_sucio_punto_coma.csv"

#Leer el archivo
df_rrhh = pd.read_csv(url_archivo_colab_rrhh, sep = ";" ,skiprows=2)

#Mostrar el archivo
display(df_rrhh)

# LABORATORIO 4

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# ARCHIVO DE PRUEBA
datos_sucios = """Reporte Confidencial de Ventas
Generado automaticamente por el sistema Legacy
id_transaccion;fecha_venta;cliente;ciudad;monto_usd
1001;2026-04-15; Ana Gomez ;lima;250.50
1002;2026-04-18;carlos ruiz;cusco;Error_Red
1003;2026/05/02; LUIS PEREZ;arequipa;1200.00
1003;2026/05/02; LUIS PEREZ;arequipa;1200.00

1004;2026-05-10;Maria Diaz;LIMA;No_Data
1005;2026-06-20;Jorge Soto;cusco;85.90"""
with open("ventas_legacy.csv", "w") as f:
 f.write(datos_sucios)

In [ ]:
lugar = "/content/ventas_legacy.csv"

In [ ]:
df_ventas = pd.read_csv(lugar, sep = ";" , skiprows=2)

In [ ]:
display(df_ventas)

   id_transaccion fecha_venta      cliente    ciudad  monto_usd
0            1001  2026-04-15   Ana Gomez       lima     250.50
1            1002  2026-04-18  carlos ruiz     cusco  Error_Red
2            1003  2026/05/02   LUIS PEREZ  arequipa    1200.00
3            1003  2026/05/02   LUIS PEREZ  arequipa    1200.00
4            1004  2026-05-10   Maria Diaz      LIMA    No_Data
5            1005  2026-06-20   Jorge Soto     cusco      85.90

2da Parte

In [ ]:
# 1. Resumen técnico del DataFrame.
# Pandas asume el tipo 'object' (texto) para monto_usd porque encontró letras ("Error_Red").
print("--- 1. Resumen Técnico ---")
df_ventas.info()

# 2. Cantidad exacta de filas y columnas
print("\n--- 2. Dimensiones de la Tabla (Filas, Columnas) ---")
print(df_ventas.shape)

# 3. Verificación de valores nulos.
# Mostrará 0 nulos inicialmente porque los errores ("No_Data") aún se leen como texto válido.
print("\n--- 3. Valores Nulos Detectados Automáticamente ---")
print(df_ventas.isnull().sum())

--- 1. Resumen Técnico ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_transaccion  6 non-null      int64
 1   fecha_venta     6 non-null      object
 2   cliente         6 non-null      object
 3   ciudad          6 non-null      object
 4   monto_usd       6 non-null      object
dtypes: int64(1), object(4)
memory usage: 372.0+ bytes

--- 2. Dimensiones de la Tabla (Filas, Columnas) ---
(6, 5)

--- 3. Valores Nulos Detectados Automáticamente ---
id_transaccion    0
fecha_venta       0
cliente           0
ciudad            0
monto_usd         0
dtype: int64

In [ ]:
df_ventas['fecha_venta'] = df_ventas['fecha_venta'].str.replace('/','-')
display(df_ventas)

   id_transaccion fecha_venta      cliente    ciudad  monto_usd
0            1001  2026-04-15   Ana Gomez       lima     250.50
1            1002  2026-04-18  carlos ruiz     cusco  Error_Red
2            1003  2026-05-02   LUIS PEREZ  arequipa    1200.00
3            1003  2026-05-02   LUIS PEREZ  arequipa    1200.00
4            1004  2026-05-10   Maria Diaz      LIMA    No_Data
5            1005  2026-06-20   Jorge Soto     cusco      85.90

In [ ]:
# 1. Casteo de Fechas: Convierte la columna a formato fecha.
# errors='coerce' fuerza la conversión y vuelve NaT (Not a Time) cualquier dato ilegible.
df_ventas['fecha_venta'] = pd.to_datetime(df_ventas['fecha_venta'], errors='coerce')

# 2. Casteo Numérico: Convierte los montos a formato número (float).
# errors='coerce' transformará los textos "Error_Red" y "No_Data" en valores nulos (NaN).
df_ventas['monto_usd'] = pd.to_numeric(df_ventas['monto_usd'], errors='coerce')

# 3. Manejo de Nulos: Ahora que los errores son NaN, los rellenamos con 0 matemáticamente seguro.
df_ventas['monto_usd'] = df_ventas['monto_usd'].fillna(0)

# 4. Eliminación de Duplicados: Borra la fila de Luis Perez que estaba repetida.
df_ventas.drop_duplicates(inplace=True)

display(df_ventas)

   id_transaccion fecha_venta      cliente    ciudad  monto_usd
0            1001  2026-04-15    Ana Gomez      LIMA      250.5
1            1002  2026-04-18  Carlos Ruiz     CUSCO        0.0
2            1003  2026-05-02   Luis Perez  AREQUIPA     1200.0
4            1004  2026-05-10   Maria Diaz      LIMA        0.0
5            1005  2026-06-20   Jorge Soto     CUSCO       85.9

In [ ]:
# 1. Limpieza de cliente: .strip() quita espacios de los bordes, .title() pone mayúscula inicial.
df_ventas['cliente'] = df_ventas['cliente'].str.strip().str.title()

# 2. Estandarización de ciudad: .upper() convierte todo a mayúsculas sostenidas.
df_ventas['ciudad'] = df_ventas['ciudad'].str.upper()

# 3. Lógica Condicional: np.where(condición, valor_si_verdadero, valor_si_falso)
df_ventas['tipo_cliente'] = np.where(df_ventas['monto_usd'] > 500, "VIP", "Regular")

display(df_ventas)

   id_transaccion fecha_venta      cliente    ciudad  monto_usd tipo_cliente
0            1001  2026-04-15    Ana Gomez      LIMA      250.5      Regular
1            1002  2026-04-18  Carlos Ruiz     CUSCO        0.0      Regular
2            1003  2026-05-02   Luis Perez  AREQUIPA     1200.0          VIP
4            1004  2026-05-10   Maria Diaz      LIMA        0.0      Regular
5            1005  2026-06-20   Jorge Soto     CUSCO       85.9      Regular

In [ ]:
# 1. Extraer el mes: El accesor .dt funciona porque ya hicimos el casteo en la Parte 3.
df_ventas['mes_operacion'] = df_ventas['fecha_venta'].dt.month

# 2. Agrupación: Agrupamos por el mes extraído y aplicamos la suma sobre la columna de montos.
# Se usan dobles corchetes [['monto_usd']] para que el resultado siga viéndose como DataFrame.
reporte_mensual = df_ventas.groupby('mes_operacion')[['monto_usd']].sum()

# 3. Mostrar el reporte gerencial final
print("--- Reporte Regional de Ventas por Mes ---")
display(reporte_mensual)

--- Reporte Regional de Ventas por Mes ---

               monto_usd
mes_operacion
4                  250.5
5                 1200.0
6                   85.9

# LABORATORIO 5

Caso de Negocio: Consolidación de Planilla y
Evaluación de Desempeño
El departamento de Recursos Humanos le ha enviado dos fuentes de datos distintas: un
reporte con los datos base de los empleados (con errores de tipeo y formatos incorrectos) y un
reporte con las evaluaciones de desempeño del último semestre. Su objetivo como Ingeniero
de Datos es limpiar la información, cruzar ambos reportes, calcular los bonos correspondientes
mediante lógicas avanzadas y exportar el archivo definitivo listo para que Finanzas realice los
pagos.

Parte 1: Creación de los Datos y Limpieza Avanzada
Cópielo y ejecute el siguiente código para cargar los DataFrames base en la memoria de su
entorno de Google Colab:

import pandas as pd
import numpy as np
# Tabla 1: Base de Empleados (Con errores intencionales)
df_empleados = pd.DataFrame({
"id_emp": ["E001", " E002 ", "e003", "E004"],
"nombre_completo": [" ana perez", "LUIS GOMEZ", "carlos ruiz", "maria diaz "],
"salario_base": ["USD 1200", "USD 1500", "USD 900", "USD 2000"]
})
# Tabla 2: Evaluaciones de Desempeño
df_evaluaciones = pd.DataFrame({
"id_empleado": ["E001", "E002", "E003", "E009"], # Nota: E009 no existe en la base
principal
"calificacion": ["A", "B", "A", "C"]
})

Misiones:
1. Limpie la columna id_emp del df_empleados. Utilice .apply(lambda x: ...) o los métodos
encadenados de .str para eliminar los espacios en blanco a los extremos y convertir
todas las letras a mayúsculas.
2. Estandarice la columna nombre_completo para que no tenga espacios sueltos a los lados
y utilice el formato de Título (Ej. "Ana Perez").
3. Limpie la columna salario_base utilizando .apply() y una función lambda para quitar el
texto "USD " y convertir el valor resultante a un número decimal (float).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_empleados = pd.DataFrame({ "id_emp": ["E001", " E002 ", "e003", "E004"], "nombre_completo": [" ana perez", "LUIS GOMEZ", "carlos ruiz", "maria diaz "], "salario_base": ["USD 1200", "USD 1500", "USD 900", "USD 2000"] })

In [ ]:
df_evaluaciones = pd.DataFrame({ "id_empleado": ["E001", "E002", "E003", "E009"],"calificacion": ["A", "B", "A", "C"] })

In [ ]:
display(df_empleados)

   id_emp nombre_completo salario_base
0    E001       ana perez     USD 1200
1   E002       LUIS GOMEZ     USD 1500
2    e003     carlos ruiz      USD 900
3    E004     maria diaz      USD 2000

In [ ]:
display(df_evaluaciones)

  id_empleado calificacion
0        E001            A
1        E002            B
2        E003            A
3        E009            C

In [ ]:
df_empleados['id_emp'] = df_empleados['id_emp'].apply(lambda x: x.strip().upper())
df_empleados['nombre_completo'] = df_empleados['nombre_completo'].apply(lambda x: x.strip().title())
df_empleados['salario_base'] = df_empleados['salario_base'].apply(lambda x: float(x.replace("USD ", "")) if isinstance(x, str) else float(x))
print("1. Datos Limpios:")
display(df_empleados)

1. Datos Limpios:

  id_emp nombre_completo  salario_base
0   E001       Ana Perez        1200.0
1   E002      Luis Gomez        1500.0
2   E003     Carlos Ruiz         900.0
3   E004      Maria Diaz        2000.0

Parte 2: Cruce de Tablas (Merge)
Ahora debe unir la información de desempeño a la base principal de empleados.
Misiones:
1. Utilice pd.merge() para realizar un cruce tipo LEFT JOIN donde df_empleados sea la
tabla "mandante" (a la izquierda). Queremos mantener a todos los empleados de la base,
tengan o no evaluación.
2. Dado que las llaves se llaman distinto (id_emp en la primera tabla vs id_empleado en la
segunda), utilice los parámetros left_on y right_on.
3. Guarde la tabla cruzada resultante en una variable llamada df_consolidado.

4. Notará que el cruce generó columnas redundantes. Elimine la columna id_empleado que
provino de la tabla de la derecha utilizando .drop(..., axis=1).

Parte 3: Lógica Condicional Multivariable (.apply con def)
Finanzas ha determinado la siguiente regla para asignar los bonos de desempeño a la planilla
cruzada.
Misiones:
1. Cree una función en Python (utilizando def) llamada calcular_bono(fila) que reciba una
fila completa de la tabla.
2. La lógica interna de la función debe ser:
○ Si la calificación es "A", el bono será equivalente al 20% del salario_base.
○ Si la calificación es "B", el bono será equivalente al 10% del salario_base.
○ Si la calificación es nula o cualquier otra letra, el bono será 0.
3. Aplique su función al df_consolidado utilizando el método .apply(..., axis=1) para crear
una nueva columna llamada bono_asignado. (Recuerde que axis=1 es vital para que la
función pueda leer múltiples columnas de la misma fila).
4. Cree una columna final llamada salario_neto que sume el salario base más el bono
asignado.

Parte 4: Fase LOAD (Exportaciones al Sistema)
El pipeline ETL no termina hasta que los datos no son cargados a su destino final.
Misiones:
1. Exporte el DataFrame final df_consolidado a un archivo plano llamado
"planilla_final_2026.csv".
2. Asegúrese de incluir el parámetro index=False para que el sistema financiero no reciba
una columna extra de números de índice sin sentido.
3. (Reto Adicional) Exporte el mismo DataFrame a un archivo de Excel (.xlsx) en una
pestaña que se llame "Planilla_Neta".

Entregable

Al finalizar, verifique en el panel de "Archivos" de Google Colab que sus documentos CSV y
Excel se hayan generado correctamente con los datos limpios. Descargue su Notebook en
formato .ipynb y súbalo a la plataforma virtual.